export const TableFields = [
  {
    title: 'Pk',
    dataIndex: 'Pk',
    width: 40,
    center: true,
  },
  {
    title: '字段名',
    dataIndex: 'Field',
    ellipsis: true,
    tooltip: true,
    width: 120,
  },
  {
    title: '类型',
    dataIndex: 'Type',
    ellipsis: true,
    tooltip: true,
    width: 120,
  },
  {
    title: 'IsNull',
    dataIndex: 'Null',
    center: true,
    ellipsis: true,
    tooltip: true,
    width: 80,
  },
  {
    title: '默认值',
    dataIndex: 'Default',
    ellipsis: true,
    tooltip: true,
    width: 120,
  },
  {
    title: '扩展信息',
    dataIndex: 'Extra',
    ellipsis: true,
    tooltip: true,
    width: 140,
  },
  {
    title: '注释',
    dataIndex: 'Comment',
    ellipsis: true,
    tooltip: true,
    width: 140,
  },
];
