/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    ConnectDialog: typeof import('./src/components/Dialog/ConnectDialog.vue')['default']
    ConnectTree: typeof import('./src/components/ConnectManager/ConnectTree.vue')['default']
    DatabasePanel: typeof import('./src/components/Panel/DatabasePanel.vue')['default']
    EditorPanel: typeof import('./src/components/Panel/EditorPanel.vue')['default']
    GridTable: typeof import('./src/components/Base/GridTable.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('./src/components/layout/Menu.vue')['default']
    PanelManager: typeof import('./src/components/Panel/PanelManager.vue')['default']
    ServerStatus: typeof import('./src/components/Dialog/ServerStatus.vue')['default']
    Statusbar: typeof import('./src/components/layout/Statusbar.vue')['default']
    Tabber: typeof import('./src/components/Tabber/Tabber.vue')['default']
    TableInformation: typeof import('./src/components/Panel/TableInformation.vue')['default']
    TablePanel: typeof import('./src/components/Panel/TablePanel.vue')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
  }
}
