/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    ConnectTree: typeof import('./src/components/ConnectManager/ConnectTree.vue')['default']
    EditorPanel: typeof import('./src/components/Panel/EditorPanel.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    PanelManager: typeof import('./src/components/Panel/PanelManager.vue')['default']
    Tabber: typeof import('./src/components/Tabber/Tabber.vue')['default']
    TablePanel: typeof import('./src/components/Panel/TablePanel.vue')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
    TreeNode: typeof import('./src/components/ConnectManager/TreeNode.vue')['default']
  }
}
