/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATree: typeof import('@arco-design/web-vue')['Tree']
    Captionbar: typeof import('./src/components/layout/Captionbar.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    ConnectDialog: typeof import('./src/components/Dialog/ConnectDialog.vue')['default']
    ConnectTree: typeof import('./src/components/ConnectManager/ConnectTree.vue')['default']
    DatabasePanel: typeof import('./src/components/Panel/DatabasePanel.vue')['default']
    EditorPanel: typeof import('./src/components/Panel/EditorPanel.vue')['default']
    GridTable: typeof import('./src/components/Base/GridTable.vue')['default']
    HistoryDrawer: typeof import('./src/components/layout/HistoryDrawer.vue')['default']
    IceButton: typeof import('./src/components/UI/IceButton.vue')['default']
    IceDialog: typeof import('./src/components/UI/IceDialog.vue')['default']
    IceDrawer: typeof import('./src/components/UI/IceDrawer.vue')['default']
    IceIcon: typeof import('./src/components/UI/IceIcon.vue')['default']
    IceIconButton: typeof import('./src/components/UI/IceIconButton.vue')['default']
    IceInput: typeof import('./src/components/UI/IceInput.vue')['default']
    IceLoading: typeof import('./src/components/UI/IceLoading.vue')['default']
    IceSplit: typeof import('./src/components/UI/IceSplit.vue')['default']
    IceTable: typeof import('./src/components/UI/IceTable.vue')['default']
    IceTabs: typeof import('./src/components/UI/IceTabs.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('./src/components/Base/Menu.vue')['default']
    PanelManager: typeof import('./src/components/Panel/PanelManager.vue')['default']
    ProcessList: typeof import('./src/components/Dialog/ProcessList.vue')['default']
    ServerStatus: typeof import('./src/components/Dialog/ServerStatus.vue')['default']
    Statusbar: typeof import('./src/components/layout/Statusbar.vue')['default']
    Tabber: typeof import('./src/components/Tabber/Tabber.vue')['default']
    TableDesignPanel: typeof import('./src/components/Panel/TableDesignPanel.vue')['default']
    TableInformation: typeof import('./src/components/Panel/TableInformation.vue')['default']
    TablePanel: typeof import('./src/components/Panel/TablePanel.vue')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
  }
}
