import field_types from 'mysql/lib/protocol/constants/types';

export const FIELD_TYPE_MAP = {
  [field_types.DECIMAL]: 'decimal',
  [field_types.TINY]: 'tinyint',
  [field_types.SHORT]: 'short',
  [field_types.LONG]: 'int',
  [field_types.FLOAT]: 'float',
  [field_types.DOUBLE]: 'double',
  [field_types.NULL]: 'null',
  [field_types.TIMESTAMP]: 'timestamp',
  [field_types.LONGLONG]: 'long',
  [field_types.INT24]: 'int24',
  [field_types.DATE]: 'date',
  [field_types.TIME]: 'time',
  [field_types.DATETIME]: 'datetime',
  [field_types.YEAR]: 'year',
  [field_types.NEWDATE]: 'newdate',
  [field_types.VARCHAR]: 'char',
  [field_types.BIT]: 'bit',
  [field_types.TIMESTAMP2]: 'timestamp2',
  [field_types.DATETIME2]: 'datetime2',
  [field_types.TIME2]: 'time2',
  [field_types.JSON]: 'json',
  [field_types.NEWDECIMAL]: 'decimal',
  [field_types.ENUM]: 'enum',
  [field_types.SET]: 'set',
  [field_types.TINY_BLOB]: 'tinyblob',
  [field_types.MEDIUM_BLOB]: 'medium_blob',
  [field_types.LONG_BLOB]: 'long_blob',
  [field_types.BLOB]: 'blog',
  [field_types.VAR_STRING]: 'varchar',
  [field_types.STRING]: 'text',
  [field_types.GEOMETRY]: 'geometry',
};
